var objectmaker={
Reg:function(id,name,password,Tests){
    this.id=id;
    this.name=name;
    this.password=password;
    this.Tests=Tests;
},
Login:function(mail,password){
    this.mail=mail;
    this.password=password;
},
makeTest:function(mail,testname,testid,isPublish,houre,minute){
this.mail=mail;
this.testname=testname;
this.testid=testid;
this.isPublish=isPublish;
this.houre=houre;
this.minute=minute;
},
makeTeacherid:function(id){
    this.mail=id;
},
makeTestname:function(testname){
    this.testname=testname;
},
makeQuestion:function(queno,question,optn1,optn2,optn3,optn4,ans,positivemark,negativemark){
    this.queno=queno;  
    this.question=question;
    this.optn1=optn1;
    this.optn2=optn2;
    this.optn3=optn3;
    this.optn4=optn4;
    this.ans=ans;
    this.positivemark=positivemark;
    this.negativemark=negativemark;
  },
}
module.exports=objectmaker;